<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Version>9.0.0-preview.1</Version>
    <PackageId>SeliseBlocks.ObservabilityDriver</PackageId>
    <Authors>SeliseBlocks</Authors>
    <Company>SeliseBlocks</Company>
    <Description>Blocks Observability Driver - Monitor and Health APIs</Description>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <IncludeOutputAssemblies>true</IncludeOutputAssemblies>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>Genesis, BlocksGenesis, SeliseBlocksGenesis, Observability, Monitor, Health, Driver</PackageTags>
    <RepositoryUrl>https://github.com/SELISEdigitalplatforms/blocks-observability</RepositoryUrl>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Transitive dependencies of Alert.DomainService bundled in this package -->
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="SeliseBlocks.Genesis" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <ProjectReference Include="..\Alert.DomainService\Alert.DomainService.csproj" PrivateAssets="All" />
    <None Remove="bin\Release\net9.0\Alert.DomainService.dll" />
    <None Include="$(OutputPath)Alert.DomainService.dll" Pack="true" PackagePath="lib/net9.0/" />
  </ItemGroup>

</Project>
